/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as FiturRouteImport } from './routes/fitur'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CaraKerjaRouteImport } from './routes/cara-kerja'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTokoRouteImport } from './routes/admin.toko'
import { Route as AdminTanamanRouteImport } from './routes/admin.tanaman'
import { Route as AdminPenggunaRouteImport } from './routes/admin.pengguna'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminRouteImport } from './routes/admin.admin'
import { Route as AuthenticatedTokoRouteImport } from './routes/_authenticated/toko'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedJadwalRouteImport } from './routes/_authenticated/jadwal'
import { Route as AuthenticatedBerandaRouteImport } from './routes/_authenticated/beranda'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const FiturRoute = FiturRouteImport.update({
  id: '/fitur',
  path: '/fitur',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraKerjaRoute = CaraKerjaRouteImport.update({
  id: '/cara-kerja',
  path: '/cara-kerja',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTokoRoute = AdminTokoRouteImport.update({
  id: '/toko',
  path: '/toko',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTanamanRoute = AdminTanamanRouteImport.update({
  id: '/tanaman',
  path: '/tanaman',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaRoute = AdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTokoRoute = AuthenticatedTokoRouteImport.update({
  id: '/toko',
  path: '/toko',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJadwalRoute = AuthenticatedJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBerandaRoute = AuthenticatedBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/faq': typeof FaqRoute
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/jadwal': typeof AuthenticatedJadwalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/scan': typeof AuthenticatedScanRoute
  '/toko': typeof AuthenticatedTokoRoute
  '/admin/admin': typeof AdminAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tanaman': typeof AdminTanamanRoute
  '/admin/toko': typeof AdminTokoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/faq': typeof FaqRoute
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/jadwal': typeof AuthenticatedJadwalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/scan': typeof AuthenticatedScanRoute
  '/toko': typeof AuthenticatedTokoRoute
  '/admin/admin': typeof AdminAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tanaman': typeof AdminTanamanRoute
  '/admin/toko': typeof AdminTokoRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/faq': typeof FaqRoute
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/_authenticated/beranda': typeof AuthenticatedBerandaRoute
  '/_authenticated/jadwal': typeof AuthenticatedJadwalRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/toko': typeof AuthenticatedTokoRoute
  '/admin/admin': typeof AdminAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tanaman': typeof AdminTanamanRoute
  '/admin/toko': typeof AdminTokoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cara-kerja'
    | '/faq'
    | '/fitur'
    | '/tentang'
    | '/beranda'
    | '/jadwal'
    | '/profil'
    | '/scan'
    | '/toko'
    | '/admin/admin'
    | '/admin/login'
    | '/admin/pengguna'
    | '/admin/tanaman'
    | '/admin/toko'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cara-kerja'
    | '/faq'
    | '/fitur'
    | '/tentang'
    | '/beranda'
    | '/jadwal'
    | '/profil'
    | '/scan'
    | '/toko'
    | '/admin/admin'
    | '/admin/login'
    | '/admin/pengguna'
    | '/admin/tanaman'
    | '/admin/toko'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/cara-kerja'
    | '/faq'
    | '/fitur'
    | '/tentang'
    | '/_authenticated/beranda'
    | '/_authenticated/jadwal'
    | '/_authenticated/profil'
    | '/_authenticated/scan'
    | '/_authenticated/toko'
    | '/admin/admin'
    | '/admin/login'
    | '/admin/pengguna'
    | '/admin/tanaman'
    | '/admin/toko'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CaraKerjaRoute: typeof CaraKerjaRoute
  FaqRoute: typeof FaqRoute
  FiturRoute: typeof FiturRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitur': {
      id: '/fitur'
      path: '/fitur'
      fullPath: '/fitur'
      preLoaderRoute: typeof FiturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-kerja': {
      id: '/cara-kerja'
      path: '/cara-kerja'
      fullPath: '/cara-kerja'
      preLoaderRoute: typeof CaraKerjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/toko': {
      id: '/admin/toko'
      path: '/toko'
      fullPath: '/admin/toko'
      preLoaderRoute: typeof AdminTokoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tanaman': {
      id: '/admin/tanaman'
      path: '/tanaman'
      fullPath: '/admin/tanaman'
      preLoaderRoute: typeof AdminTanamanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna': {
      id: '/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AdminPenggunaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin': {
      id: '/admin/admin'
      path: '/admin'
      fullPath: '/admin/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/toko': {
      id: '/_authenticated/toko'
      path: '/toko'
      fullPath: '/toko'
      preLoaderRoute: typeof AuthenticatedTokoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jadwal': {
      id: '/_authenticated/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof AuthenticatedJadwalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beranda': {
      id: '/_authenticated/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof AuthenticatedBerandaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBerandaRoute: typeof AuthenticatedBerandaRoute
  AuthenticatedJadwalRoute: typeof AuthenticatedJadwalRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedTokoRoute: typeof AuthenticatedTokoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBerandaRoute: AuthenticatedBerandaRoute,
  AuthenticatedJadwalRoute: AuthenticatedJadwalRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedTokoRoute: AuthenticatedTokoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPenggunaRoute: typeof AdminPenggunaRoute
  AdminTanamanRoute: typeof AdminTanamanRoute
  AdminTokoRoute: typeof AdminTokoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPenggunaRoute: AdminPenggunaRoute,
  AdminTanamanRoute: AdminTanamanRoute,
  AdminTokoRoute: AdminTokoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CaraKerjaRoute: CaraKerjaRoute,
  FaqRoute: FaqRoute,
  FiturRoute: FiturRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
